"""
config.py
=========
Central configuration. Everything that differs between "test against SITL" and
"real flight on the Pi" lives HERE and nowhere else - drone.py, mission.py,
failsafe.py and the state machine are identical either way.

The DEFAULTS BELOW ARE THE FLIGHT CONFIGURATION. Reading this file tells you how the
real aircraft is set up - drop servo on a Pi GPIO, the 4S Li-Ion threshold, the
camera-less "timed" source. The constructors at the bottom only pick an endpoint:

    Config.pi()         -> UDP to mavlink-router on the Pi (the default profile)
    Config.pi_serial()  -> direct UART, for a setup WITHOUT mavlink-router
    Config.sitl()       -> UDP to the simulator

Every deviation from reality lives in exactly ONE place, Config.sitl(), and there are
three of them: the drop servo ("fc" - a Mac has no GPIO), the battery threshold
(10.8 V - SITL's simulated pack sits at 12.6 V) and the camera source ("auto" ->
SimCamera). That asymmetry is deliberate: main.py flies the real aircraft by default
and needs --sim to simulate, so a forgotten flag fails on the safe side.
"""

from dataclasses import dataclass


@dataclass
class Config:
    # ------------------------------------------------------------------
    # Connection
    # ------------------------------------------------------------------
    # SITL: sim_vehicle.py outputs MAVLink on port 14550 by default. Our script
    # is the RECEIVER, so it must bind/listen -> use "udpin:".
    #   connection_string = "udpin:127.0.0.1:14550"   (SITL native on the Mac)
    #   connection_string = "udpin:0.0.0.0:14550"     (SITL in a container;
    #     listen on all interfaces, SITL sends with --out udp:<YOUR-MAC-IP>:14550)
    #
    # To run alongside QGroundControl (which takes 14550), add a second output in
    # the MAVProxy console with `output add 127.0.0.1:14551` and use port 14551.
    #
    # Real Pi on the flight controller (serial UART link):
    #   connection_string = "/dev/serial0"   and baud = 921600 (or 57600)
    #   Alternatively via USB-UART adapter: "/dev/ttyUSB0"
    connection_string: str = "udpin:127.0.0.1:14550"
    baud: int = 115200            # only used for a serial connection
    gcs_system_id: int = 255      # the ID we announce as the ground station
    is_simulation: bool = False

    # ------------------------------------------------------------------
    # Mission / target
    # ------------------------------------------------------------------
    # target_lat/lon and cruise_alt drive the GPS/outdoor path (ENROUTE -> OVER_TARGET),
    # which is Phase-1 SITL/GPS shakedown heritage: these are the SITL start point (CMAC,
    # Canberra) slightly offset, kept so that path still flies against the simulator. The
    # REAL mission is GPS-denied and navigates in local NED (see gps_denied below), where
    # the target is FOUND by the camera, not flown to by coordinate - so these values do
    # not describe a real delivery point and are not meant to be edited into one.
    target_lat: float = -35.36272
    target_lon: float = 149.16523
    cruise_alt: float = 10.0       # GPS-path flight altitude [m] (relative to start)
    arrival_radius_m: float = 1.5  # target counts as reached within this distance

    # ------------------------------------------------------------------
    # Payload / release
    # ------------------------------------------------------------------
    # Where the drop servo is wired (see release.py):
    #   "fc" = on a flight-controller output, driven over MAVLink (SITL / tests).
    #   "pi" = on a Raspberry Pi GPIO pin, PWM generated by the Pi itself (real
    #          indoor build - the FC is not involved in the release).
    # DEFAULT = the real aircraft. Config.sitl() switches this to "fc".
    release_mechanism: str = "pi"
    drop_servo: int = 9            # "fc": servo output (SERVO9 = AUX OUT 1 on many FCs)
    drop_gpio_pin: int = 18        # "pi": BCM GPIO pin (18 = phys pin 12, hardware-PWM capable)
    drop_pwm: int = 1900           # release pulse [us] (hatch open) - used by both paths
    neutral_pwm: int = 1100        # rest pulse [us] (hatch closed) - used by both paths

    # ------------------------------------------------------------------
    # Failsafe / safety
    # ------------------------------------------------------------------
    # Abort threshold [V] for the REAL pack: 4S Li-Ion (4.1 V/cell full = 16.4 V,
    # 2.8 V/cell empty = 11.2 V) -> ~12.8 V. DEFAULT = the real aircraft. SITL's
    # simulated pack sits at 12.6 V and would trip this on the first reading, so
    # Config.sitl() lowers it to 10.8 V. Note that only the VOLTAGE arm is relaxed
    # there - battery_min_percent below stays active in every profile.
    battery_min_voltage: float = 12.8
    battery_min_percent: int = 20       # abort threshold, remaining capacity [%]
    # A single sagging reading is not an empty battery: Li-Ion dips hard under load.
    # Only this many consecutive readings below the threshold abort the mission.
    battery_low_samples: int = 3
    phase_timeout_s: float = 60.0       # max duration per mission phase
    heartbeat_timeout_s: float = 3.0    # no FC heartbeat within this -> LINK_LOSS
    telemetry_max_misses: int = 5       # consecutive missing telemetry reads -> NO_TELEMETRY

    # FENCE / ENVELOPE LIMITS ARE NOT CONFIGURED HERE ANY MORE. Since the 2026-08-24
    # ownership decision the companion writes NO FC parameter: the fence, the envelope
    # limits (WPNAV_SPEED, WPNAV_SPEED_UP, RTL_ALT) and their values all live in
    # params/flight_v2.param, owned by Mission Planner. failsafe.verify_fence_disabled()
    # only READS the fence and refuses to fly if one is armed. The hard-won reason a
    # fence is OFF indoors, kept so it does not vanish from the code: an altitude fence
    # is only as good as the altitude it is fed, and near the ground propeller downwash
    # spikes the BAROMETRIC altitude (4.05 / 4.65 / 5.26 / 4.73 / 6.73 m across our five
    # flight logs, centimetres off the floor). A 4 m fence breached on EVERY takeoff, and
    # FENCE_ACTION=2 forced the vehicle out of the pilot's mode into LAND - twice an
    # auto-disarm nobody asked for, once (diverged EKF altitude) LAND at full throttle
    # into the ceiling. A barometric altitude fence sized for an indoor hover sits inside
    # its own sensor's noise band, and a fence whose action is a MODE CHANGE turns a bad
    # measurement into a manoeuvre nobody commanded.

    # Abort if the FC leaves this mode. The pilot flipping out of GUIDED, a fence
    # breach or an EKF failsafe all change the mode behind our back - from that moment
    # every setpoint we send is ignored, and commanding any mode would OVERRIDE the human.
    # So we notice and stop sending. Empty string disables the check.
    expect_mode: str = "GUIDED"

    # ------------------------------------------------------------------
    # Flight-parameter verification before every mission (read-only)
    # ------------------------------------------------------------------
    # The companion writes no FC parameter (ownership decision 2026-08-24), which only
    # works if something notices when the live aircraft has drifted away from the
    # published set. So the mission reads a curated subset back from the FC before it
    # arms and compares it against the published file. It still writes nothing: a
    # difference is reported, and the fix is made in Mission Planner.
    #
    #   "abort" = refuse to fly when a CRITICAL parameter differs (the default)
    #   "warn"  = report every difference and fly anyway
    #   "off"   = skip the check entirely
    #
    # See paramcheck.py for which parameters are critical and why. The informational
    # ones (ARMING_CHECK, the FLTMODE map, the battery thresholds) are always reported
    # and never block, because the team is knowingly carrying differences there.
    param_check: str = "abort"
    # Which published file to compare against. Empty = resolve the highest-numbered one
    # automatically: params/flight_v<N>.param for the aircraft, the generated mirror
    # params/sitl_flight_v<N>.parm for a simulated run. Publishing a v3 therefore needs
    # no source edit. Set a path to pin one file (--expected does the same for
    # preflight.py).
    expected_params_path: str = ""

    # ------------------------------------------------------------------
    # Recovery: what we do after the drop and on every abort
    # ------------------------------------------------------------------
    # "land" = descend where we are. Indoors this is almost always right: LAND needs no
    #          position estimate, no home and no altitude headroom.
    # "rtl"  = fly back to the launch point. OUTDOOR ONLY - RTL first CLIMBS to RTL_ALT
    #          before returning, which in a hall means flying into the ceiling.
    recovery_action: str = "land"

    # ------------------------------------------------------------------
    # Flyaway protection (GPS-denied)
    # ------------------------------------------------------------------
    # An optical-flow position estimate that loses its height reference does not fail
    # loudly - it DRIFTS, and the position controller then flies full-throttle after an
    # error that exists only in the filter. Our own params/README.md records 366 m of
    # drift measured while the vehicle stood still, caused by a rangefinder stuck at
    # 0.00 m. The altitude geofence does not help: it guards the ceiling, not the walls.
    #
    # Two guards, both cheap:
    #   1. Before arming, prove the sensors that feed the estimate actually produce data.
    #   2. In flight, abort if the reported position leaves a plausible envelope.
    #
    # Two checks, because the ground cannot tell you everything: before arming we only
    # prove the sensors STREAM (on the floor a healthy rangefinder reads ~0 m, so its
    # value proves nothing there), and right after the climb we prove the rangefinder
    # actually FOLLOWS the height. That second one is the real gate, and it runs at
    # takeoff altitude where an abort is a short descent.
    verify_position_sensors: bool = True
    sensor_check_s: float = 5.0         # how long to listen before deciding
    rangefinder_min_valid_m: float = 0.02   # below this counts as "no reading"
    # In the air the rangefinder must report at least this fraction of the commanded
    # altitude. Loose on purpose - the question is "does it respond to height at all",
    # not "is it accurate".
    rangefinder_track_fraction: float = 0.4
    # Abort if the local position estimate leaves this radius of the EKF origin. Sized
    # from the search pattern, not the hall: the spiral reaches search_max_radius_m plus
    # one search_step_m, so anything well beyond that is the filter running away rather
    # than the aircraft flying. 0 disables the check.
    max_position_radius_m: float = 15.0
    # The VERTICAL twin, checked continuously in failsafe.check(): abort when the EKF
    # altitude and the raw rangefinder disagree by more than this. The 2026-08-21 crash
    # had exactly this signature (EKF -1070 m, rangefinder 0.02 m, on the floor). The
    # rangefinder measures distance to the SURFACE below, so flying over tall clutter
    # can disagree legitimately - hence a loose threshold plus several consecutive
    # samples before aborting. 0 disables the check.
    alt_disagree_max_m: float = 2.0
    alt_disagree_samples: int = 3

    # ------------------------------------------------------------------
    # Target alignment (visual servoing over the target before the drop)
    # ------------------------------------------------------------------
    # dx/dy from every Camera are GROUND METRES, so these are metres too - 0.15 means
    # 15 cm, not 15 % of the image.
    centre_tolerance: float = 0.15  # |dx|,|dy| below this counts as "centred" [m]
    approach_gain: float = 0.5      # P gain: body metres moved per metre of ground error
    max_nudge_m: float = 0.3        # clamp for a single correction step [m]
    nudge_settle_s: float = 0.5     # wait after each nudge so the move settles
    approach_lost_max: int = 5      # consecutive "target lost" frames before back to SEARCH

    # ------------------------------------------------------------------
    # Navigation mode (Phase 2 — indoor, GPS-denied)
    # ------------------------------------------------------------------
    # gps_denied=True: position comes from optical flow (MTF-01P), navigation is in
    # local NED, pre-arm waits for the RELATIVE EKF position. False = the GPS/Phase-1
    # path (global lat/lon, absolute EKF position).
    gps_denied: bool = True
    search_altitude: float = 1.0        # indoor cruise/search height [m]
    local_arrival_radius_m: float = 0.5  # local-NED waypoint reached within this [m]

    # EKF origin (Phase 3). Indoors there is no GPS to seed the EKF origin/home, so the
    # companion sends SET_GPS_GLOBAL_ORIGIN before arming. Any sensible reference works —
    # it only anchors the local NED frame + home. Enable for a truly GPS-off run; leave
    # off when SITL still has GPS (which seeds the origin itself).
    set_origin_on_start: bool = True
    # Reference origin = the real hall (from Google Maps). Indoor nav is purely relative,
    # so only the magnetic declination + map display depend on this value; using the true
    # location gives the correct compass heading. NOTE for SITL: the simulator's compass is
    # modelled at its own home (CMAC/Canberra by default), so launch sim_vehicle at the same
    # spot - sim_vehicle.py ... --custom-location=50.131196,8.692972,112,0 - or expect a
    # small yaw offset (the mission still works, the local frame is just rotated a few deg).
    origin_lat: float = 50.13119602511582   # hall latitude  [deg]
    origin_lon: float = 8.692972038286195   # hall longitude [deg]
    origin_alt: float = 112.0               # approx hall altitude [m AMSL]; indoor height comes from LiDAR

    # ------------------------------------------------------------------
    # Hardware bring-up (staged first flights, Phase 7)
    # ------------------------------------------------------------------
    # The full mission has four unknowns at once on a new aircraft: position hold,
    # search pattern, detector and release. These two switches let you add them ONE at
    # a time, so a failure names its own cause instead of leaving you guessing.
    #
    #   1. arm_test_s > 0                   -> arm, hold on the ground, disarm. No takeoff.
    #   2. hover_test_s > 0                 -> climb, hold, land. Position hold only.
    #   3. + camera_source = "real"         -> same flight, but log what the detector
    #                                          sees directly below (it is not acted on).
    #   4. hover_test_s = 0                 -> fly the search pattern.
    #   5. + skip_drop = True               -> search, detect, centre - release nothing.
    #   6. skip_drop = False                -> the full delivery.
    #
    # hover_test_s: seconds to hold position after takeoff before landing. 0 = off.
    hover_test_s: float = 0.0
    # Altitude for the hover test [m]. 0 = use the normal takeoff altitude. Set this to
    # fly the bring-up hover lower than the search altitude without touching the rest.
    hover_test_alt: float = 0.0
    # Seconds to remain armed on the ground before commanding disarm. 0 = normal
    # mission. This mode runs the normal pre-arm setup but never enters TAKEOFF.
    arm_test_s: float = 0.0
    # Run the approach but do NOT release. The mission goes APPROACH -> RECOVER.
    skip_drop: bool = False

    # ------------------------------------------------------------------
    # Pilot-assisted start (takeover)
    # ------------------------------------------------------------------
    # The companion does not arm and does not take off: the PILOT flies the first metre
    # by hand, the companion inherits an aircraft that is already stable in the air.
    #
    # This is not only a safety preference. A flow-only vehicle may not report
    # EKF_POS_HORIZ_REL while it sits on the floor - optical flow needs height before
    # the filter trusts it - which deadlocks a companion that insists on a position
    # estimate BEFORE arming. Flying the first metre by hand breaks that circle.
    takeover_mode: bool = False
    takeover_min_alt_m: float = 0.8     # hand over above this height [m] - measured by
                                        # the RANGEFINDER, not the EKF (see below)
    takeover_timeout_s: float = 120.0   # give up waiting for the pilot after this
    takeover_ekf_wait_s: float = 10.0   # how long to wait for the EKF bit once airborne
    # Refuse the takeover when EKF altitude and rangefinder disagree by more than this.
    # A large disagreement is the diverged-vertical-estimate signature of the 2026-08-21
    # crash (EKF read +1070 m on the ground while the rangefinder read 0.02 m): handing
    # a GUIDED aircraft to a filter in that state is the flyaway setup.
    takeover_alt_disagree_m: float = 1.5

    # ------------------------------------------------------------------
    # Search pattern (Phase 2)
    # ------------------------------------------------------------------
    search_pattern: str = "spiral"   # "spiral" (expanding square, default) or "lawnmower"
    search_step_m: float = 1.0       # spacing between search legs / rings [m]
    search_max_radius_m: float = 6.0  # spiral: stop expanding beyond this [m]
    search_area_w_m: float = 6.0     # lawnmower: rectangle width (east) [m]
    search_area_h_m: float = 6.0     # lawnmower: rectangle height (north) [m]
    detection_cadence: str = "stop_and_look"  # "stop_and_look" (default) or "continuous"
    look_settle_s: float = 0.5       # hover time before detecting at a waypoint [s]
    # SEARCH needs its own budget: the default spiral has 25 waypoints, so reusing
    # phase_timeout_s (60 s) for the whole phase aborts long before the pattern is
    # flown. waypoint_timeout_s bounds a SINGLE leg, search_timeout_s the whole phase.
    # Sized from a measurement, not a guess: the default spiral (25 waypoints, 169 m of
    # path) took 219 s end to end in SITL at WPNAV_SPEED = 100 cm/s on 2026-09-21. The
    # old 300 s left 27 % headroom, which a slower real aircraft would eat, and the
    # abort would then land mid-pattern under the honest but unhelpful name
    # TIMEOUT_SEARCH. Raise this together with search_max_radius_m: the path grows with
    # the square of the radius.
    search_timeout_s: float = 420.0
    waypoint_timeout_s: float = 30.0
    # Consecutive unreachable waypoints before we give up. Repeatedly missing a
    # waypoint means the vehicle is not following us (mode changed) or the position
    # estimate has diverged - flying the rest of the pattern from an unknown place
    # would only make things worse.
    search_max_misses: int = 3

    # ------------------------------------------------------------------
    # Simulation target (SimCamera pretends the pad is here, local NED [m])
    # ------------------------------------------------------------------
    # Deliberately NOT on a spiral corner. The pattern visits (2.0, 2.0) exactly, and
    # with the target there the drone arrives already centred: APPROACH returns DROP on
    # its first frame and the visual-servoing loop - the whole point of the milestone-5
    # rehearsal - is never executed. Placed half a step off, the same run has to nudge
    # its way in. (The unit tests had picked these values for that reason long before
    # the SITL default caught up; found in a full milestone sweep on 2026-09-21.)
    sim_target_north: float = 2.5
    sim_target_east: float = 1.5
    sim_fov_radius_m: float = 1.5    # camera "sees" the target within this ground radius

    # ------------------------------------------------------------------
    # Camera selection (which Camera implementation main.py wires in)
    # ------------------------------------------------------------------
    # "auto" = SimCamera when gps_denied else MockCamera; "sim" / "mock" force one;
    # "timed" = TimedCamera (finds the target after a set time, no real detection) to
    # flight-test the search pattern + drop without the AI camera (Phase 3);
    # "real" = RealCamera (Raspberry Pi AI Camera / IMX500, Phase 4);
    # "none" = a camera that never detects anything. Used by the ground arm test,
    #          position-hold test and pattern-only test (milestones 1, 2 and 4).
    #
    # DEFAULT = "timed", the honest camera-less default for the real aircraft. It must
    # NOT be "auto" here: on the drone "auto" resolves to SimCamera, which invents a
    # target at sim_target_north/east and reports it detected - the aircraft would fly
    # to a spot where nothing is and drop the payload there. Set "real" once
    # camera_model_path points at a real .rpk. Config.sitl() switches this to "auto".
    camera_source: str = "timed"
    # Which bring-up milestone this run is (set by --milestone, 0 = a normal mission).
    # Recorded so the flight log says which stage produced it.
    milestone: int = 0
    # Set when a milestone asked for the real camera but the run is a simulation, so
    # the simulated detector was substituted. Logged, never silent.
    milestone_camera_substituted: bool = False
    timed_camera_after_s: float = 20.0  # TimedCamera: declare "found" after this many seconds

    # ------------------------------------------------------------------
    # Real AI camera (IMX500) — Phase 4
    # ------------------------------------------------------------------
    # The IMX500 runs the network on the SENSOR and needs Sony's packaged .rpk format.
    # A .tflite does NOT load here - it would have to run on the Pi's CPU, which a
    # Zero 2 W cannot do at a useful rate. Produce the .rpk with
    #   yolo export model=<trained>.pt format=imx      (Linux/Docker)
    #   imx500-package -i packerOut.zip -o <outdir>    (on the Pi)
    camera_model_path: str = "/home/drone/models/pad/network.rpk"
    camera_labels_path: str = "/home/drone/models/pad/labels.txt"
    camera_confidence: float = 0.7   # ignore detections below this score. SCALE IS 0..1
                                 # (0.7 = 70 %) - entering 70 here would reject every
                                 # detection. Team decision 2026-08-24 for the pad .rpk.
    # Which class counts as the landing pad. None = accept any detected class. Set this
    # for a multi-class model: chasing the wrong class is worse than not detecting.
    camera_target_class: int | None = None
    camera_fps: int = 15             # sensor frame rate; the mission polls far slower
    camera_warmup_s: float = 2.0     # discard frames until auto-exposure has settled

    # --- Mounting calibration (see docs/SIM_TO_REAL.md §3) ---------------
    # The image->body mapping depends on how the camera is physically rotated in its
    # mount, so it MUST be verified on the real airframe. These settings exist so that
    # calibration is a parameter change instead of a source edit between test flights.
    # Procedure: hover, place the pad clearly to the drone's RIGHT, and check that the
    # logged dx is POSITIVE. Repeat with the pad AHEAD for dy.
    cam_swap_axes: bool = False      # camera rotated 90° in its mount
    cam_invert_x: bool = False       # positive dx must mean "target is to the right"
    cam_invert_y: bool = False       # positive dy must mean "target is ahead"
    # Field of view of the IMX500 lens, used to turn image angles into ground metres.
    # Raspberry Pi AI Camera, stock lens, full sensor area: 66° x 52.3° (78.3° diagonal).
    # Correct these if you crop, switch sensor mode or change the lens - RealCamera scales
    # every correction with them, so a wrong FOV mis-scales the whole approach loop.
    # Both assume a NADIR (straight-down) mount: the metre conversion treats the ground as
    # perpendicular to the optical axis. A tilted camera needs the tilt angle folded in.
    cam_hfov_deg: float = 66.0
    cam_vfov_deg: float = 52.3
    # Coordinate ORDER of the boxes the .rpk emits. "yxyx" is the IMX500 / picamera2
    # sample convention; Ultralytics `format=imx` exports have been seen emitting
    # "xyxy" (and input-tensor PIXELS instead of 0..1 fractions - the pixel case is
    # normalised automatically, the order cannot be guessed and must be set here).
    # Verify at milestone 3: hold the pad clearly to one side and check the logged
    # dx/dy signs - a wrong order shows up as swapped axes.
    cam_box_order: str = "yxyx"

    # ------------------------------------------------------------------
    # Logging
    # ------------------------------------------------------------------
    log_dir: str = "logs"          # directory for timestamped mission log files

    # ------------------------------------------------------------------
    # Convenience constructors
    # ------------------------------------------------------------------
    @classmethod
    def sitl(cls, host: str = "127.0.0.1", port: int = 14550) -> "Config":
        """Preset for testing against SITL. Use host=0.0.0.0 if SITL runs in a container.

        This is the ONLY place where simulation values live. The dataclass defaults
        above describe the real aircraft, so anything not overridden here is flight
        configuration - which is the point: the simulation deviates from reality in
        exactly three named ways, and they are visible in one place.

        1. `release_mechanism="fc"` - a Mac has no GPIO, so the drop is simulated on an
           FC output that SITL echoes back (this also gives us a read-back to verify).
        2. `battery_min_voltage=10.8` - SITL's simulated pack sits at ~12.6 V, so the
           real 12.8 V threshold would abort the mission on the first reading.
        3. `camera_source="auto"` - resolves to SimCamera/MockCamera. On the real
           aircraft this would be dangerous (see the field comment above), which is why
           it is set here rather than being the shared default.

        `is_simulation=True` is not a fourth deviation but the label on the other three:
        it states plainly what the profile is, so the banner, the fresh-SITL hint and the
        choice of expected parameter file stop inferring it from the drop servo.
        """
        return cls(
            connection_string=f"udpin:{host}:{port}",
            is_simulation=True,
            release_mechanism="fc",
            battery_min_voltage=10.8,
            camera_source="auto",
        )

    @classmethod
    def pi(cls, host: str = "127.0.0.1", port: int = 14550) -> "Config":
        """Preset for the real Raspberry Pi - and yes, this is a UDP link, not a serial one.

        mavlink-router owns /dev/serial0 and forwards the FC stream to
        127.0.0.1:14550, so the script binds there exactly like it does against SITL.
        Two processes cannot share the UART, which is why Config.pi_serial() is only
        for setups WITHOUT a router.

        Note what this constructor does NOT do: it overrides nothing except the
        endpoint. The dataclass defaults above ARE the flight configuration - drop servo
        on a Pi GPIO, the 4S Li-Ion threshold, the camera-less "timed" source. That is
        deliberate: reading config.py now tells you how the real aircraft is set up, and
        every deviation from it lives in exactly one place, Config.sitl().
        """
        return cls(connection_string=f"udpin:{host}:{port}")

    @classmethod
    def pi_serial(cls, device: str = "/dev/serial0", baud: int = 921600) -> "Config":
        """Preset for a DIRECT UART link to the flight controller, i.e. WITHOUT
        mavlink-router. Use Config.pi() when the router is running (our setup).

        Like Config.pi(), this only changes the endpoint - everything else is already
        the flight configuration by default."""
        return cls(connection_string=device, baud=baud)
