"""
config.py
=========
Central configuration. Everything that differs between "test against SITL" and
"real flight on the Pi" lives HERE and nowhere else - drone.py, mission.py,
failsafe.py and the state machine are identical either way.

Use the convenience constructors at the bottom rather than editing fields by hand;
they encode the whole SITL/Pi delta:

    Config.sitl()  -> UDP to the simulator, drop servo on an FC output, SITL battery
    Config.pi()    -> UDP to mavlink-router on the Pi, drop servo on a GPIO pin,
                      4S Li-Ion battery threshold

(It used to be true that the connection string was the *only* difference. It no
longer is - the drop servo and the battery pack are genuinely different hardware -
so the presets exist to keep that difference in one place.)
"""

from dataclasses import dataclass


@dataclass
class Config:
    # ------------------------------------------------------------------
    # Connection
    # ------------------------------------------------------------------
    # SITL: sim_vehicle.py outputs MAVLink on port 14550 by default. Our script
    # is the RECEIVER, so it must bind/listen -> use "udpin:".
    #   connection_string = "udpin:127.0.0.1:14550"   (SITL native on the Mac)
    #   connection_string = "udpin:0.0.0.0:14550"     (SITL in a container;
    #     listen on all interfaces, SITL sends with --out udp:<YOUR-MAC-IP>:14550)
    #
    # To run alongside QGroundControl (which takes 14550), add a second output in
    # the MAVProxy console with `output add 127.0.0.1:14551` and use port 14551.
    #
    # Real Pi on the flight controller (serial UART link):
    #   connection_string = "/dev/serial0"   and baud = 921600 (or 57600)
    #   Alternatively via USB-UART adapter: "/dev/ttyUSB0"
    connection_string: str = "udpin:127.0.0.1:14550"
    baud: int = 115200            # only used for a serial connection
    gcs_system_id: int = 255      # the ID we announce as the ground station

    # ------------------------------------------------------------------
    # Mission / target
    # ------------------------------------------------------------------
    # Default target = the SITL start point (CMAC, Canberra) slightly offset.
    # Replace with real coordinates for an actual flight.
    target_lat: float = -35.36272
    target_lon: float = 149.16523
    cruise_alt: float = 10.0       # flight altitude in metres (relative to start)
    arrival_radius_m: float = 1.5  # target counts as reached within this distance

    # ------------------------------------------------------------------
    # Payload / release
    # ------------------------------------------------------------------
    # Where the drop servo is wired (see release.py):
    #   "fc" = on a flight-controller output, driven over MAVLink (SITL / tests).
    #   "pi" = on a Raspberry Pi GPIO pin, PWM generated by the Pi itself (real
    #          indoor build - the FC is not involved in the release).
    release_mechanism: str = "fc"
    drop_servo: int = 9            # "fc": servo output (SERVO9 = AUX OUT 1 on many FCs)
    drop_gpio_pin: int = 18        # "pi": BCM GPIO pin (18 = phys pin 12, hardware-PWM capable)
    drop_pwm: int = 1900           # release pulse [us] (hatch open) - used by both paths
    neutral_pwm: int = 1100        # rest pulse [us] (hatch closed) - used by both paths

    # ------------------------------------------------------------------
    # Failsafe / safety
    # ------------------------------------------------------------------
    # Abort threshold [V]. NOTE: this depends on the pack and is therefore set by the
    # convenience constructors, not here: our drone flies 4S Li-Ion (4.1 V/cell full =
    # 16.4 V, 2.8 V/cell empty = 11.2 V), so a real abort threshold is ~12.8 V. SITL's
    # simulated pack sits at 12.6 V, which would trip that instantly - Config.sitl()
    # therefore lowers it. The value below is only the dataclass default.
    battery_min_voltage: float = 12.8
    battery_min_percent: int = 20       # abort threshold, remaining capacity [%]
    # A single sagging reading is not an empty battery: Li-Ion dips hard under load.
    # Only this many consecutive readings below the threshold abort the mission.
    battery_low_samples: int = 3
    phase_timeout_s: float = 60.0       # max duration per mission phase
    geofence_enable: bool = True        # set FENCE_ENABLE?
    # FENCE_TYPE bitmask. 1 = max altitude only — works WITHOUT a horizontal position,
    # so it is indoor-safe (a circle/polygon fence would need GPS/position). Outdoor you
    # can add the circle bit (2) / polygon bit (4).
    fence_type: int = 1
    # Size the altitude fence to the flight: indoor ~ search_altitude (default 2 m).
    # NOTE: for the GPS path raise this above cruise_alt (10 m) or it trips on takeoff.
    fence_alt_max_m: float = 4.0        # max altitude for the fence [m]
    heartbeat_timeout_s: float = 3.0    # no FC heartbeat within this -> LINK_LOSS
    telemetry_max_misses: int = 5       # consecutive missing telemetry reads -> NO_TELEMETRY

    # Abort if the FC leaves this mode. The pilot flipping out of GUIDED, a fence
    # breach or an EKF failsafe all change the mode behind our back - from that moment
    # every setpoint we send is ignored, and commanding RTL would OVERRIDE the human.
    # So we notice and stop sending. Empty string disables the check.
    expect_mode: str = "GUIDED"

    # ------------------------------------------------------------------
    # Recovery: what we do after the drop and on every abort
    # ------------------------------------------------------------------
    # "land" = descend where we are. Indoors this is almost always right: LAND needs no
    #          position estimate, no home and no altitude headroom.
    # "rtl"  = fly back to the launch point. OUTDOOR ONLY - RTL first CLIMBS to RTL_ALT
    #          before returning, which in a hall means flying into the ceiling.
    recovery_action: str = "land"

    # ------------------------------------------------------------------
    # FC-side safety envelope (set + verified by the companion before every flight)
    # ------------------------------------------------------------------
    # These are NOT companion logic - they are what the autopilot does on its own when
    # something goes wrong, and its defaults are made for outdoor flight: FENCE_ACTION
    # defaults to 1 ("RTL or Land") and RTL climbs to RTL_ALT (default 15 m). We set
    # them explicitly rather than trusting whatever is stored in the FC.
    enforce_safety_envelope: bool = True
    fence_action: int = 2           # 2 = Always Land (1 = RTL or Land -> climbs first)
    rtl_alt_m: float = 2.0          # RTL altitude [m], in case RTL is triggered anyway
    climb_rate_cms: float = 50.0    # WPNAV_SPEED_UP [cm/s]. The default 250 overshoots
                                    # a 2 m takeoff by >2 m and trips a low fence.

    # ------------------------------------------------------------------
    # Target alignment (visual servoing over the target before the drop)
    # ------------------------------------------------------------------
    centre_tolerance: float = 0.15  # |dx|,|dy| below this counts as "centred"
    approach_gain: float = 0.5      # body metres to nudge per unit of image offset
    max_nudge_m: float = 0.3        # clamp for a single correction step [m]
    nudge_settle_s: float = 0.5     # wait after each nudge so the move settles
    approach_lost_max: int = 5      # consecutive "target lost" frames before back to SEARCH

    # ------------------------------------------------------------------
    # Navigation mode (Phase 2 — indoor, GPS-denied)
    # ------------------------------------------------------------------
    # gps_denied=True: position comes from optical flow (MTF-01P), navigation is in
    # local NED, pre-arm waits for the RELATIVE EKF position. False = the GPS/Phase-1
    # path (global lat/lon, absolute EKF position).
    gps_denied: bool = True
    search_altitude: float = 2.0        # indoor cruise/search height [m]
    local_arrival_radius_m: float = 0.5  # local-NED waypoint reached within this [m]

    # EKF origin (Phase 3). Indoors there is no GPS to seed the EKF origin/home, so the
    # companion sends SET_GPS_GLOBAL_ORIGIN before arming. Any sensible reference works —
    # it only anchors the local NED frame + home. Enable for a truly GPS-off run; leave
    # off when SITL still has GPS (which seeds the origin itself).
    set_origin_on_start: bool = True
    # Reference origin = the real hall (from Google Maps). Indoor nav is purely relative,
    # so only the magnetic declination + map display depend on this value; using the true
    # location gives the correct compass heading. NOTE for SITL: the simulator's compass is
    # modelled at its own home (CMAC/Canberra by default), so launch sim_vehicle at the same
    # spot - sim_vehicle.py ... --custom-location=50.131196,8.692972,112,0 - or expect a
    # small yaw offset (the mission still works, the local frame is just rotated a few deg).
    origin_lat: float = 50.13119602511582   # hall latitude  [deg]
    origin_lon: float = 8.692972038286195   # hall longitude [deg]
    origin_alt: float = 112.0               # approx hall altitude [m AMSL]; indoor height comes from LiDAR

    # ------------------------------------------------------------------
    # Search pattern (Phase 2)
    # ------------------------------------------------------------------
    search_pattern: str = "spiral"   # "spiral" (expanding square, default) or "lawnmower"
    search_step_m: float = 1.0       # spacing between search legs / rings [m]
    search_max_radius_m: float = 6.0  # spiral: stop expanding beyond this [m]
    search_area_w_m: float = 6.0     # lawnmower: rectangle width (east) [m]
    search_area_h_m: float = 6.0     # lawnmower: rectangle height (north) [m]
    detection_cadence: str = "stop_and_look"  # "stop_and_look" (default) or "continuous"
    look_settle_s: float = 0.5       # hover time before detecting at a waypoint [s]
    # SEARCH needs its own budget: the default spiral has 25 waypoints, so reusing
    # phase_timeout_s (60 s) for the whole phase aborts long before the pattern is
    # flown. waypoint_timeout_s bounds a SINGLE leg, search_timeout_s the whole phase.
    search_timeout_s: float = 300.0
    waypoint_timeout_s: float = 30.0
    # Consecutive unreachable waypoints before we give up. Repeatedly missing a
    # waypoint means the vehicle is not following us (mode changed) or the position
    # estimate has diverged - flying the rest of the pattern from an unknown place
    # would only make things worse.
    search_max_misses: int = 3

    # ------------------------------------------------------------------
    # Simulation target (SimCamera pretends the pad is here, local NED [m])
    # ------------------------------------------------------------------
    sim_target_north: float = 2.0
    sim_target_east: float = 2.0
    sim_fov_radius_m: float = 1.5    # camera "sees" the target within this ground radius

    # ------------------------------------------------------------------
    # Camera selection (which Camera implementation main.py wires in)
    # ------------------------------------------------------------------
    # "auto" = SimCamera when gps_denied else MockCamera; "sim" / "mock" force one;
    # "timed" = TimedCamera (finds the target after a set time, no real detection) to
    # flight-test the search pattern + drop without the AI camera (Phase 3).
    camera_source: str = "auto"
    timed_camera_after_s: float = 20.0  # TimedCamera: declare "found" after this many seconds

    # ------------------------------------------------------------------
    # Logging
    # ------------------------------------------------------------------
    log_dir: str = "logs"          # directory for timestamped mission log files

    # ------------------------------------------------------------------
    # Convenience constructors
    # ------------------------------------------------------------------
    @classmethod
    def sitl(cls, host: str = "127.0.0.1", port: int = 14550) -> "Config":
        """Preset for testing against SITL. Use host=0.0.0.0 if SITL runs in a container.

        Also picks the two settings that genuinely differ from the real aircraft:
        the drop servo lives on an FC output (there is no GPIO on the Mac), and the
        battery threshold matches SITL's simulated ~12.6 V pack instead of our 4S
        Li-Ion. Everything else is identical to the flight configuration on purpose.
        """
        return cls(
            connection_string=f"udpin:{host}:{port}",
            release_mechanism="fc",
            battery_min_voltage=10.8,
        )

    @classmethod
    def pi(cls, host: str = "127.0.0.1", port: int = 14550) -> "Config":
        """Preset for the real Raspberry Pi - and yes, this is a UDP link, not a serial one.

        mavlink-router owns /dev/serial0 and forwards the FC stream to
        127.0.0.1:14550, so the script binds there exactly like it does against SITL.
        Two processes cannot share the UART, which is why Config.pi_serial() is only
        for setups WITHOUT a router.
        """
        return cls(
            connection_string=f"udpin:{host}:{port}",
            release_mechanism="pi",
            battery_min_voltage=12.8,
        )

    @classmethod
    def pi_serial(cls, device: str = "/dev/serial0", baud: int = 921600) -> "Config":
        """Preset for a DIRECT UART link to the flight controller, i.e. WITHOUT
        mavlink-router. Use Config.pi() when the router is running (our setup)."""
        return cls(
            connection_string=device,
            baud=baud,
            release_mechanism="pi",
            battery_min_voltage=12.8,
        )